#!/bin/zsh

echo Updating Prezto Repo
pushd ~/.zprezto
git pull && git submodule update --init --recursive
popd

echo Updating Spacemacs Repo
pushd ~/.emacs.d
git pull 
git submodule sync; git submodule update
popd

